### ISSUE TITLE
Immersive Article with no mainMedia renders badly

### ISSUE THREAD

**Issue by sammorrisdesign** [guardian/mobile-apps-article-templates#539]
An immersive article with no `mainMedia` still renders as if it is expecting `mainMedia`.

App:
![image](https://cloud.githubusercontent.com/assets/1607666/18489783/177ad0c8-79cd-11e6-82ab-164108211405.png)

I'd expect something similar to the web templates:
![image](https://cloud.githubusercontent.com/assets/1607666/18489929/cb68e264-79cd-11e6-8c39-c98c96638636.png)

**Comment by webb04** [comment]
Has been fixed and released.
