### ISSUE TITLE
Immersive embeds aren't full width, render with chapter header even though there shouldn't be one

### ISSUE THREAD

**Issue by sammorrisdesign** [guardian/mobile-apps-article-templates#540]
The immersive weighting on embeds should make them full width.

It also looks like it's getting the immersive + h2 chapter header too as well. This should only happen when it's an immersive image followed by a h2. Here it's happening with a html embed with no h2 following it 😕 

![image](https://cloud.githubusercontent.com/assets/1607666/18490123/a1ca557c-79ce-11e6-8602-3d81ab08d19c.png)

**Comment by webb04** [comment]
Looks to be fixed now:
![IMG_7440](https://user-images.githubusercontent.com/11618797/58713147-f12da680-83b9-11e9-9b37-42b0326a24fb.PNG)
